[plugin:vite:import-analysis] Failed to resolve import "firebase/auth" from "src/services/authService.ts". Does the file exist?
/mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/src/services/authService.ts:9:7
6  |    sendPasswordResetEmail,
7  |    updateProfile
8  |  } from "firebase/auth";
   |          ^
9  |  import { auth } from "../config/firebase";
10 |  export const authService = {
    at TransformPluginContext._formatLog (file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:42517:41)
    at TransformPluginContext.error (file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:42514:16)
    at normalizeUrl (file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:40493:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:40612:37
    at async Promise.all (index 0)
    at async TransformPluginContext.transform (file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:40539:7)
    at async EnvironmentPluginContainer.transform (file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:42312:18)
    at async loadAndTransform (file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:35738:27)
    at async viteTransformMiddleware (file:///mnt/c/Users/speci/Desktop/Varie/Syd_Prototipo/node_modules/vite/dist/node/chunks/dep-Bu492Fnd.js:37253:24





